### Obtener todas las tiendas
GET http://localhost:3000/stores

###
GET http://localhost:3000/stores/1


### Crear una tienda
POST http://localhost:3000/stores
Content-Type: application/json

{
    "name": "Casa Salud del Llano",
    "address": "Carrera 4",
    "isActive": true,
    "city": "Maní"
}

### Actualizar una tienda
PUT http://localhost:3000/stores/1