### Obtener todas las tiendas
GET http://localhost:3000/stores

###
GET http://localhost:3000/stores/1


### Crear una tienda
POST http://localhost:3000/stores
Content-Type: application/json

{
    "name": "",
    "isActive": true,
    "address": "Carrera 4",
    "products": [
        {
            "productId": 1,
            "amount": 30
        }
    ]
}

### Actualizar una tienda
PUT http://localhost:3000/stores/1